import SwiftUI

struct ProjectDetailView: View {
    @Environment(AppRepository.self) private var repository; let projectID: UUID
    @State private var showingPayment = false; @State private var showingResult = false
    private var project: Project? { repository.projects.first { $0.id == projectID } }
    var body: some View { Group { if let project { let metrics = ProjectMetrics(project: project, sessions: repository.sessions); ScrollView { VStack(alignment: .leading, spacing: 20) { VStack(alignment: .leading, spacing: 7) { HStack { StatusBadge(text: project.status.rawValue); StatusBadge(text: project.priority.rawValue, color: project.priority == .high ? HWTheme.warning : HWTheme.purple) }; Text(project.clientName).foregroundStyle(HWTheme.secondary); Label(project.dueDate.formatted(date: .long, time: .omitted), systemImage: "calendar").font(.subheadline) }; Button { } label: { Label("Track time", systemImage: "timer").frame(maxWidth: .infinity, minHeight: 44) }.buttonStyle(.borderedProminent); metricGrid(metrics); section("Tasks", action: nil) { if project.tasks.isEmpty { Text("No tasks yet").foregroundStyle(HWTheme.secondary) } else { ForEach(project.tasks) { task in Button { repository.toggleTask(task.id, projectID: project.id) } label: { HStack { Image(systemName: task.status == .completed ? "checkmark.circle.fill" : "circle").foregroundStyle(task.status == .completed ? HWTheme.success : HWTheme.secondary); Text(task.title).strikethrough(task.status == .completed); Spacer(); Text(task.priority.rawValue).font(.caption).foregroundStyle(HWTheme.secondary) } }.buttonStyle(.plain).padding(.vertical, 5) } } }; section("Payments", action: { showingPayment = true }) { if project.payments.isEmpty { Text("No payments recorded").foregroundStyle(HWTheme.secondary) } else { ForEach(project.payments) { payment in HStack { VStack(alignment: .leading) { Text(payment.method); Text(payment.date.formatted(date: .abbreviated, time: .omitted)).font(.caption).foregroundStyle(HWTheme.secondary) }; Spacer(); Text(payment.amount.money).fontWeight(.semibold); StatusBadge(text: payment.status.rawValue, color: payment.status == .paid ? HWTheme.success : HWTheme.warning) } } } }; if project.status != .completed { Button("Complete project") { showingResult = true }.buttonStyle(.bordered).frame(maxWidth: .infinity) } }.padding(20) }.background(HWTheme.background).navigationTitle(project.title).navigationBarTitleDisplayMode(.inline).sheet(isPresented: $showingPayment) { PaymentFormView(projectID: project.id) }.sheet(isPresented: $showingResult) { CompletionView(projectID: project.id) } } else { ContentUnavailableView("Project not found", systemImage: "briefcase") } } }
    private func metricGrid(_ metrics: ProjectMetrics) -> some View { HWCard { Grid(horizontalSpacing: 22, verticalSpacing: 18) { GridRow { metric("Progress", metrics.progress.formatted(.percent.precision(.fractionLength(0)))); metric("Tracked", metrics.trackedHours.hoursLabel) }; GridRow { metric("Received", metrics.received.money); metric("Pending", metrics.pending.money) }; GridRow { metric("Effective rate", metrics.effectiveRate.money + "/h"); metric("Project value", metrics.value.money) } } } }
    private func metric(_ label: String, _ value: String) -> some View { VStack(alignment: .leading, spacing: 4) { Text(label).font(.caption).foregroundStyle(HWTheme.secondary); Text(value).font(.headline).monospacedDigit() }.frame(maxWidth: .infinity, alignment: .leading) }
    private func section<Content: View>(_ title: String, action: (() -> Void)?, @ViewBuilder content: () -> Content) -> some View { VStack(alignment: .leading, spacing: 10) { HStack { Text(title).font(.title3.bold()); Spacer(); if let action { Button(action: action) { Image(systemName: "plus.circle.fill") }.accessibilityLabel("Add \(title.lowercased())") } }; HWCard { VStack(alignment: .leading, spacing: 10) { content() } } } }
}

struct CompletionView: View {
    @Environment(\.dismiss) private var dismiss; @Environment(AppRepository.self) private var repository; let projectID: UUID
    var body: some View { if let project = repository.projects.first(where: { $0.id == projectID }) { let metrics = ProjectMetrics(project: project, sessions: repository.sessions), result = CompletionResult(project: project, metrics: metrics); NavigationStack { ScrollView { VStack(spacing: 22) { Image(systemName: result.health == .strong ? "checkmark.seal.fill" : "chart.bar.doc.horizontal.fill").font(.system(size: 62)).foregroundStyle(result.health == .strong ? HWTheme.success : HWTheme.purple); VStack(spacing: 8) { Text(project.title).font(.title.bold()); StatusBadge(text: result.health.rawValue, color: result.health == .strong ? HWTheme.success : HWTheme.warning); Text(result.message).multilineTextAlignment(.center).foregroundStyle(HWTheme.secondary) }; HWCard { VStack(spacing: 14) { resultRow("Project value", metrics.value.money); resultRow("Tracked", metrics.trackedHours.hoursLabel + " / " + project.estimatedHours.hoursLabel); resultRow("Effective rate", metrics.effectiveRate.money + " /h"); resultRow("Target rate", project.desiredRate.money + " /h") } }; Button("Finish") { var updated = project; updated.status = .completed; repository.update(updated); dismiss() }.buttonStyle(.borderedProminent).controlSize(.large).frame(maxWidth: .infinity) }.padding(24) }.navigationTitle("Project result").navigationBarTitleDisplayMode(.inline) } } }
    private func resultRow(_ label: String, _ value: String) -> some View { HStack { Text(label).foregroundStyle(HWTheme.secondary); Spacer(); Text(value).fontWeight(.semibold).monospacedDigit() } }
}

