import SwiftUI

struct TrackView: View {
    @Environment(AppRepository.self) private var repository; @State private var projectID: UUID?; @State private var note = ""; @State private var showingManual = false
    private var selected: Project? { repository.projects.first { $0.id == projectID } }
    var body: some View { ScrollView { VStack(spacing: HWSpacing.extraExtraLarge) { if let session = repository.activeSession { TimelineView(.periodic(from: .now, by: 1)) { context in VStack(spacing: HWSpacing.small) { StatusBadge(text: Localizable.Tracking.timerRunning, color: HWTheme.success); Text(session.projectTitle).font(.title2.bold()); Text(context.date.timeIntervalSince(session.startedAt).clock).font(.system(size: 52, weight: .medium, design: .monospaced)).minimumScaleFactor(0.7) } }; Button { repository.stop() } label: { Label(Localizable.Tracking.stopTimer, systemImage: "stop.fill").frame(maxWidth: .infinity, minHeight: HWSpacing.controlHeight) }.buttonStyle(.borderedProminent).tint(.red) } else { VStack(spacing: HWSpacing.small) { Image(systemName: "timer").font(.system(size: 46)).foregroundStyle(HWTheme.purple); Text(Localizable.Tracking.ready).font(.title2.bold()); Text(Localizable.Tracking.readyMessage).foregroundStyle(HWTheme.secondary).multilineTextAlignment(.center) }; HWCard { VStack(alignment: .leading, spacing: HWSpacing.large) { Text(Localizable.Common.project).font(.caption).foregroundStyle(HWTheme.secondary); Picker("Project", selection: $projectID) { Text(Localizable.Common.selectProject).tag(UUID?.none); ForEach(repository.projects.filter { $0.status == .active }) { Text($0.title).tag(Optional($0.id)) } }; Divider(); TextField(Localizable.Tracking.sessionNote, text: $note) } }; Button { if let selected { repository.start(project: selected, note: note) } } label: { Label(Localizable.Tracking.startTimer, systemImage: "play.fill").frame(maxWidth: .infinity, minHeight: HWSpacing.controlHeight) }.buttonStyle(.borderedProminent).disabled(selected == nil) }; Button { showingManual = true } label: { Label(Localizable.Tracking.addManually, systemImage: "plus.circle") }.buttonStyle(.bordered); if !repository.sessions.isEmpty { VStack(alignment: .leading, spacing: HWSpacing.medium) { Text(Localizable.Tracking.recentSessions).font(.title3.bold()); ForEach(repository.sessions.prefix(4)) { session in HWCard { HStack { VStack(alignment: .leading) { Text(session.projectTitle).font(.headline); Text(session.startedAt.formatted(date: .abbreviated, time: .shortened)).font(.caption).foregroundStyle(HWTheme.secondary) }; Spacer(); Text(session.duration.durationLabel).monospacedDigit() } } } } } }.padding(HWSpacing.extraLarge) }.background(HWTheme.background).navigationTitle(Localizable.Tracking.title).sheet(isPresented: $showingManual) { ManualSessionView() } }
}

struct ManualSessionView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(AppRepository.self) private var repository
    @State private var projectID: UUID?
    @State private var hours = 1.0
    @State private var date = Date()
    @State private var note = ""
    var body: some View { NavigationStack { Form { Picker("Project", selection: $projectID) { Text(Localizable.Common.selectProject).tag(UUID?.none); ForEach(repository.projects.filter { $0.status == .active }) { Text($0.title).tag(Optional($0.id)) } }; DatePicker("Started", selection: $date); Stepper("Duration: \(hours.hoursLabel)", value: $hours, in: 0.25...24, step: 0.25); TextField("Note (optional)", text: $note) }.navigationTitle(Localizable.Tracking.manualEntry).toolbar { ToolbarItem(placement: .cancellationAction) { Button(Localizable.Common.cancel) { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button(Localizable.Common.save) { if let project = repository.projects.first(where: { $0.id == projectID }) { repository.addManualSession(project: project, hours: hours, date: date, note: note); dismiss() } }.disabled(projectID == nil) } } } }
}
