import SwiftUI

struct TrackView: View {
    @Environment(AppRepository.self) private var repository; @State private var projectID: UUID?; @State private var note = ""; @State private var showingManual = false
    private var selected: Project? { repository.projects.first { $0.id == projectID } }
    var body: some View { ScrollView { VStack(spacing: 26) { if let session = repository.activeSession { TimelineView(.periodic(from: .now, by: 1)) { context in VStack(spacing: 8) { StatusBadge(text: "Timer running", color: HWTheme.success); Text(session.projectTitle).font(.title2.bold()); Text(context.date.timeIntervalSince(session.startedAt).clock).font(.system(size: 52, weight: .medium, design: .monospaced)).minimumScaleFactor(0.7) } }; Button { repository.stop() } label: { Label("Stop timer", systemImage: "stop.fill").frame(maxWidth: .infinity, minHeight: 52) }.buttonStyle(.borderedProminent).tint(.red) } else { VStack(spacing: 8) { Image(systemName: "timer").font(.system(size: 46)).foregroundStyle(HWTheme.purple); Text("Ready when you are").font(.title2.bold()); Text("Choose a project and keep the focus on the work.").foregroundStyle(HWTheme.secondary).multilineTextAlignment(.center) }; HWCard { VStack(alignment: .leading, spacing: 14) { Text("Project").font(.caption).foregroundStyle(HWTheme.secondary); Picker("Project", selection: $projectID) { Text("Select a project").tag(UUID?.none); ForEach(repository.projects.filter { $0.status == .active }) { Text($0.title).tag(Optional($0.id)) } }; Divider(); TextField("Session note (optional)", text: $note) } }; Button { if let selected { repository.start(project: selected, note: note) } } label: { Label("Start timer", systemImage: "play.fill").frame(maxWidth: .infinity, minHeight: 52) }.buttonStyle(.borderedProminent).disabled(selected == nil) }; Button { showingManual = true } label: { Label("Add time manually", systemImage: "plus.circle") }.buttonStyle(.bordered); if !repository.sessions.isEmpty { VStack(alignment: .leading, spacing: 12) { Text("Recent sessions").font(.title3.bold()); ForEach(repository.sessions.prefix(4)) { session in HWCard { HStack { VStack(alignment: .leading) { Text(session.projectTitle).font(.headline); Text(session.startedAt.formatted(date: .abbreviated, time: .shortened)).font(.caption).foregroundStyle(HWTheme.secondary) }; Spacer(); Text(session.duration.durationLabel).monospacedDigit() } } } } } }.padding(22) }.background(HWTheme.background).navigationTitle("Track").sheet(isPresented: $showingManual) { ManualSessionView() } }
}

struct ManualSessionView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(AppRepository.self) private var repository
    @State private var projectID: UUID?
    @State private var hours = 1.0
    @State private var date = Date()
    @State private var note = ""
    var body: some View { NavigationStack { Form { Picker("Project", selection: $projectID) { Text("Select a project").tag(UUID?.none); ForEach(repository.projects.filter { $0.status == .active }) { Text($0.title).tag(Optional($0.id)) } }; DatePicker("Started", selection: $date); Stepper("Duration: \(hours.hoursLabel)", value: $hours, in: 0.25...24, step: 0.25); TextField("Note (optional)", text: $note) }.navigationTitle("Manual entry").toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("Save") { if let project = repository.projects.first(where: { $0.id == projectID }) { repository.addManualSession(project: project, hours: hours, date: date, note: note); dismiss() } }.disabled(projectID == nil) } } } }
}
